# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        mantresdebs3:
            entity:
                class: AppBundle\Entity\Usuario
                property: nombreUsuario

    encoders:
        AppBundle\Entity\Usuario: plaintext

    role-hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: usuario_entrar
                check_path: usuario_entrar
                always_use_default_target_path: true
                default_target_path: inicio

            # Al añadir aquí el logout podemos dejar en blanco la ruta para salir de la aplicación
            logout:
                path: usuario_salir